/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;
import com.mycompany.appsistemaestoque.dao.NotaEntradaDAO;
import com.mycompany.appsistemaestoque.model.NotaEntrada;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caioh
 */
public class ConsultaNotaEntrada extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaNotaEntrada
     */
    public ConsultaNotaEntrada() {
        initComponents();
        carregarTabela();
        configurarMenuContexto();
    }
    
    //monta o cabeçalho e preenche a tabela com os dados do banco
    public void carregarTabela() {
        //1. define as colunas da tabela
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Data de Entrada");
        model.addColumn("ID do Fornecedor");
        model.addColumn("Valor Total");
        
        //2. busca as notas no banco via DAO
        List<NotaEntrada> lista = new NotaEntradaDAO().listar();
        
        //3. adiciona cada nota como uma linha da tabela
        for (NotaEntrada n : lista) {
            model.addRow(new Object[]{
                n.getId(),
                n.getDataEntrada(),
                n.getIdFornecedor(),
                n.getValorTotal()
            });
        }
        
        jTable1.setModel(model);
    }
    
    //metodo para abrir menu ao clicar com o botão direito do mouse
    private void configurarMenuContexto() {
        JPopupMenu popup = new JPopupMenu();
        JMenuItem itemAlterar = new JMenuItem("Alterar");
        JMenuItem itemExcluir = new JMenuItem("Excluir");
        popup.add(itemAlterar);
        popup.add(itemExcluir);
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger() || javax.swing.SwingUtilities.isRightMouseButton(evt)) {
                    int linha = jTable1.rowAtPoint(evt.getPoint());
                    if (linha >= 0) {
                        jTable1.setRowSelectionInterval(linha, linha); //seleciona a linha clicada
                        popup.show(jTable1, evt.getX(), evt.getY());
                    }
                }
            }
        });
        
        itemExcluir.addActionListener(e -> excluirLinhaSelecionada());
        itemAlterar.addActionListener(e -> alterarLinhaSelecionada());
    }
    
    //método para excluir cadastro
    private void excluirLinhaSelecionada() {
        int linha = jTable1.getSelectedRow();
        if (linha < 0) return;

        int id = (int) jTable1.getValueAt(linha, 0); //coluna 0 = ID

        int resposta = JOptionPane.showConfirmDialog(this,
            "Deseja realmente excluir o produto ID " + id + "?",
            "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            NotaEntrada n = new NotaEntrada();
            n.setId(id);
            new NotaEntradaDAO().excluirNotaEntrada(n);
            carregarTabela(); //atualiza a lista após excluir
        }
    }
    
    //metodo para alterar cadastro
    private void alterarLinhaSelecionada() {
        int linha = jTable1.getSelectedRow();
        if (linha < 0) return;
        
        //monta uma Nota com os dados da linha selecionada
        NotaEntrada n = new NotaEntrada();
        n.setId((int) jTable1.getValueAt(linha, 0));
        n.setDataEntrada((LocalDate) jTable1.getValueAt(linha, 1));
        n.setIdFornecedor((int) jTable1.getValueAt(linha, 2));
        n.setValorTotal((double) jTable1.getValueAt(linha, 3));
        
        EditarNotaEntrada dialog = new EditarNotaEntrada(null, true, n, this);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Notas de Entrada");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Data de Entrada", "ID do Fornecedor", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
