/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;


import com.mycompany.appsistemaestoque.dao.TipoProdutoDAO;
import com.mycompany.appsistemaestoque.model.TipoProduto;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Henrique
 */
public class ConsultaTipoProdutoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaTipoProdutoView
     */
    public ConsultaTipoProdutoView() {
        initComponents();
        preencherTabela(); 
        configurarMenuContexto();
    }
    
    public void preencherTabela() {
        TipoProdutoDAO dao = new TipoProdutoDAO();
        java.util.List<TipoProduto> lista = dao.listarTipos(); 

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        modelo.setNumRows(0);

        for (TipoProduto tp : lista) {
            modelo.addRow(new Object[]{
                tp.getId(),         
                tp.getDescricao()   
            });
        }
    }
    private void configurarMenuContexto() {
        JPopupMenu popup = new JPopupMenu();
        JMenuItem itemAlterar = new JMenuItem("Alterar");
        JMenuItem itemExcluir = new JMenuItem("Excluir");
        popup.add(itemAlterar);
        popup.add(itemExcluir);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if (evt.isPopupTrigger() || javax.swing.SwingUtilities.isRightMouseButton(evt)) {
                    int linha = jTable1.rowAtPoint(evt.getPoint());
                    if (linha >= 0) {
                        jTable1.setRowSelectionInterval(linha, linha); // Seleciona a linha clicada
                        popup.show(jTable1, evt.getX(), evt.getY());
                    }
                }
            }
        });

        itemExcluir.addActionListener(e -> excluirLinhaSelecionada());
        itemAlterar.addActionListener(e -> alterarLinhaSelecionada());
    }

    // --- MÉTODO PARA EXCLUIR ---
    private void excluirLinhaSelecionada() {
        int linha = jTable1.getSelectedRow();
        if (linha < 0) return;

        int id = (int) jTable1.getValueAt(linha, 0); // Coluna 0 = ID

        int resposta = JOptionPane.showConfirmDialog(this,
            "Deseja realmente excluir o tipo de produto ID " + id + "?",
            "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

       if (resposta == JOptionPane.YES_OPTION) {
            new TipoProdutoDAO().excluir(id); // Passa o ID direto, que é o que o DAO pede!
            preencherTabela(); // Atualiza a lista após excluir
        }
    }

    // --- MÉTODO PARA ALTERAR ---
    private void alterarLinhaSelecionada() {
        int linha = jTable1.getSelectedRow();
        if (linha < 0) return;

        TipoProduto tipo = new TipoProduto();
        tipo.setId((int) jTable1.getValueAt(linha, 0));
        tipo.setDescricao((String) jTable1.getValueAt(linha, 1));

        EditarTipoProdutoView dialog = new EditarTipoProdutoView(null, true, tipo, this);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta Tipo de Produto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
