/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.FornecedorDAO;
import com.mycompany.appsistemaestoque.model.Fornecedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cadu0
 */
public class ConsultaFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaFornecedor
     */
    public ConsultaFornecedor() {
        initComponents();
        carregarTabela();
    }
 
    //monta o cabeçalho e preenche a tabela com os dados do banco
    private void carregarTabela() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Razão Social");
        model.addColumn("CNPJ");
        model.addColumn("Telefone");
 
        List<Fornecedor> lista = new FornecedorDAO().listar();
 
        for (Fornecedor f : lista) {
            model.addRow(new Object[]{
                f.getID(),
                f.getRazaoSocial(),
                f.getCNPJ(),
                f.getTelefone()
            });
        }
 
        jTable1.setModel(model);
    }
 
    // Pega os dados da linha selecionada na tabela e monta um Fornecedor
    // Retorna null (e avisa o usuário) se nenhuma linha estiver selecionada
    private Fornecedor pegarFornecedorSelecionado() {
        int linha = jTable1.getSelectedRow();
 
        if (linha == -1) {
            JOptionPane.showMessageDialog(this,
                "Selecione um fornecedor na tabela primeiro!",
                "Nenhum fornecedor selecionado",
                JOptionPane.WARNING_MESSAGE);
            return null;
        }
 
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setID((Integer) jTable1.getValueAt(linha, 0));
        fornecedor.setRazaoSocial((String) jTable1.getValueAt(linha, 1));
        fornecedor.setCNPJ((String) jTable1.getValueAt(linha, 2));
        fornecedor.setTelefone((String) jTable1.getValueAt(linha, 3));
        return fornecedor;
    }
 
    // Abre a tela de Cadastro já preenchida, em modo de edição
    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {
        Fornecedor selecionado = pegarFornecedorSelecionado();
        if (selecionado == null) {
            return; // nada selecionado, aviso já foi mostrado
        }
 
        FornecedorView telaEdicao = new FornecedorView(selecionado);
 
        // ao fechar a tela de edição (depois de salvar), atualiza a tabela
        telaEdicao.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                carregarTabela();
            }
        });
 
        getDesktopPane().add(telaEdicao);
        telaEdicao.setVisible(true);
    }
 
    // Exclui o fornecedor selecionado, com confirmação antes
    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {
        Fornecedor selecionado = pegarFornecedorSelecionado();
        if (selecionado == null) {
            return;
        }
 
        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir \"" + selecionado.getRazaoSocial() + "\"?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION);
 
        if (confirmacao != JOptionPane.YES_OPTION) {
            return;
        }
 
        new FornecedorDAO().excluir(selecionado);
        carregarTabela(); // atualiza a lista depois de excluir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Fornecedores");
        setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Razão Social", "CNPJ", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
