/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.ItemNotaEntradaDAO;
import javax.swing.JOptionPane;
import com.mycompany.appsistemaestoque.model.ItemNotaEntrada;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Henrique
 */
public class EditarItensNotaEntrada extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarItemNotaEntrada
     */
    
    private ItemNotaEntrada item;
    private ItensNotaEntradaView telaConsulta;
    
   public EditarItensNotaEntrada(ItemNotaEntrada item, ItensNotaEntradaView telaConsulta) {
        initComponents();
        this.item = item;
        this.telaConsulta = telaConsulta;
        preencherCampos();
    }
    
    private void preencherCampos() {
        //joga a quantidade do banco no campo de texto
        jTextField1.setText(String.valueOf(item.getQuantidade()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jAtualizaritem = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Itens Nota Entrada");

        jLabel1.setText("Quantidade:");

        jAtualizaritem.setText("Atualizar Item");
        jAtualizaritem.addActionListener(this::jAtualizaritemActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jAtualizaritem)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jAtualizaritem)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAtualizaritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizaritemActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A quantidade não pode ficar vazia!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            //pega o texto e converte para número inteiro
            int novaQuantidade = Integer.parseInt(jTextField1.getText().trim());
            item.setQuantidade(novaQuantidade);
            
            //manda para o DAO atualizar no banco de dados
            ItemNotaEntradaDAO dao = new ItemNotaEntradaDAO();
            dao.alterar(item); 
            
            JOptionPane.showMessageDialog(this, "Quantidade atualizada com sucesso!");
            
            telaConsulta.atualizarTabela();
            this.dispose(); 
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Digite apenas números inteiros!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_jAtualizaritemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtualizaritem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
