/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.ProdutoDAO;
import com.mycompany.appsistemaestoque.dao.TipoProdutoDAO;
import com.mycompany.appsistemaestoque.model.Produto;
import com.mycompany.appsistemaestoque.model.TipoProduto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author heito
 */
public class EditarProdutoView extends javax.swing.JDialog {
    
    private Produto produto;
    private ConsultaProdutosView telaConsulta; //referência pra atualizar a tabela depois de salvar
    
    /**
     * Creates new form EditarProduto
     */
        //construtor recebe o produto selecionado e a tela de consulta pra atualizar depois
        public EditarProdutoView(java.awt.Frame parent, boolean modal, Produto produto, ConsultaProdutosView telaConsulta) {
        super(parent, modal); //chama o construtor do JDialog
        initComponents(); //inicia o layout
        this.produto = produto;
        this.telaConsulta = telaConsulta;
        carregarComboTipos(); //preenche o combo antes de usar os dados do produto
        preencherCampos(); //preenche os campos com os dados do produto recebido
    }
    //preenche o combo de tipos com os dados do banco
    private void carregarComboTipos() {
    List<TipoProduto> tipos = new TipoProdutoDAO().listarTipos();
    for (TipoProduto t : tipos) {
        jCBTipo.addItem(t);
    }
    }
    //preenche os campos com os dados do produto selecionado na tabela
    private void preencherCampos() {
        jTFDescricao.setText(produto.getDescricao());
        jTFValorUnitario.setText(String.valueOf(produto.getValorUnitario()));
        jTFQuantidade.setText(String.valueOf(produto.getQuantidade()));
    //seleciona no combo o tipo que já é o do produto
        for (int i = 0; i < jCBTipo.getItemCount(); i++) {
            TipoProduto t = jCBTipo.getItemAt(i);
            if (t.getId() == produto.getTipoId()) {
                jCBTipo.setSelectedItem(t); //encontrou, marca no combo e para o loop
                break;
            }
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDescricao = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jLQuantidade = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jLValorUnitario = new javax.swing.JLabel();
        jTFValorUnitario = new javax.swing.JTextField();
        jBAtualizarCadastro = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLDescricao.setText("Descrição");

        jLQuantidade.setText("Quantidade");

        jLTipo.setText("Tipo");

        jLValorUnitario.setText("Valor Unitário");

        jBAtualizarCadastro.setText("Atualizar Cadastro");
        jBAtualizarCadastro.addActionListener(this::jBAtualizarCadastroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAtualizarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addComponent(jTFQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLValorUnitario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jBAtualizarCadastro)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarCadastroActionPerformed
        // TODO add your handling code here:
        //valida campos vazios 
        if (jTFDescricao.getText().isEmpty() || jTFValorUnitario.getText().isEmpty()
            || jTFQuantidade.getText().isEmpty() || jCBTipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return; //interrompe, não deixa salvar com campo vazio
        }
        try {
            //converte e atualiza o objeto produto
            produto.setDescricao(jTFDescricao.getText());
            produto.setValorUnitario(Double.parseDouble(jTFValorUnitario.getText())); //converte string pra double
            produto.setQuantidade(Integer.parseInt(jTFQuantidade.getText())); //converte string pra int
            //pega o tipo selecionado no combo e extrai o ID real
            TipoProduto tipoSelecionado = (TipoProduto) jCBTipo.getSelectedItem();
            produto.setTipoId(tipoSelecionado.getId());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return; //interrompe, valor digitado não é número válido
        }
        //salva no banco
        new ProdutoDAO().alterarProduto(produto);
        JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
        //atualiza a tabela da tela de consulta e fecha o diálogo
        telaConsulta.carregarTabela();
        dispose(); //fecha o JDialog
 
    }//GEN-LAST:event_jBAtualizarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizarCadastro;
    private javax.swing.JComboBox<TipoProduto> jCBTipo;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLValorUnitario;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextField jTFValorUnitario;
    // End of variables declaration//GEN-END:variables
}
