/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.NotaEntradaDAO;
import com.mycompany.appsistemaestoque.model.NotaEntrada;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author caioh
 */
public class EditarNotaEntradaView extends javax.swing.JDialog {

    private NotaEntrada nota;
    private ConsultaNotaEntradaView telaConsulta; //referência pra atualizar a tabela depois de salvar
    
    /**
     * Creates new form EditarNotaEntrada
     */
    
    public EditarNotaEntradaView(java.awt.Frame parent, boolean modal, NotaEntrada nota, ConsultaNotaEntradaView telaConsulta) {
        super(parent, modal);
        initComponents();
        this.nota = nota;
        this.telaConsulta = telaConsulta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDataDeEntrada = new javax.swing.JLabel();
        jTDataDeEntrada = new javax.swing.JTextField();
        jLValorTotal = new javax.swing.JLabel();
        jTValorTotal = new javax.swing.JTextField();
        jBAtualizarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLDataDeEntrada.setText("Data de Entrada:");

        jLValorTotal.setText("Valor Total:");

        jBAtualizarCadastro.setText("Atualizar Cadastro");
        jBAtualizarCadastro.addActionListener(this::jBAtualizarCadastroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jBAtualizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLDataDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDataDeEntrada)
                            .addComponent(jLValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLDataDeEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTDataDeEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jBAtualizarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarCadastroActionPerformed
        // TODO add your handling code here:
        try {
        // TODO add your handling code here:
        // Converte a String para LocalDate (formato esperado: AAAA-MM-DD)
        nota.setDataEntrada(java.time.LocalDate.parse(jTDataDeEntrada.getText().trim()));
        nota.setValorTotal(Double.parseDouble(jTValorTotal.getText().replace(",", "."))); // Replace previne erro se digitar vírgula
        
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos no Valor Total!", "Erro", JOptionPane.ERROR_MESSAGE);
        return; // Para a execução aqui
    } catch (java.time.format.DateTimeParseException ex) {
        // CATCH NOVO: Captura o erro da data incompleta ou formatada errada
        JOptionPane.showMessageDialog(this, "Data inválida! Digite o formato completo: AAAA-MM-DD (Ex: 2025-07-28)", "Erro de Data", JOptionPane.ERROR_MESSAGE);
        return; // Para a execução aqui
    }
        
    //4. salva no banco
    new NotaEntradaDAO().alterarNotaEntrada(nota);
    JOptionPane.showMessageDialog(this, "Nota de Entrada alterada com sucesso!");
        
    //5. atualiza a tabela da tela de consulta e fecha o diálogo
    telaConsulta.carregarTabela();
    dispose();
    }//GEN-LAST:event_jBAtualizarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizarCadastro;
    private javax.swing.JLabel jLDataDeEntrada;
    private javax.swing.JLabel jLValorTotal;
    private javax.swing.JTextField jTDataDeEntrada;
    private javax.swing.JTextField jTValorTotal;
    // End of variables declaration//GEN-END:variables
}
