/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.ProdutoDAO;
import com.mycompany.appsistemaestoque.dao.TipoProdutoDAO;
import com.mycompany.appsistemaestoque.model.Produto;
import com.mycompany.appsistemaestoque.model.TipoProduto;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author heito
 */
public class EditarProduto extends javax.swing.JDialog {
    
    private Produto produto;
    private ConsultaProdutos telaConsulta; //referência pra atualizar a tabela depois de salvar
    
    /**
     * Creates new form EditarProduto
     */
        public EditarProduto(java.awt.Frame parent, boolean modal, Produto produto, ConsultaProdutos telaConsulta) {
        super(parent, modal);
        initComponents();
        this.produto = produto;
        this.telaConsulta = telaConsulta;
        carregarComboTipos();
        preencherCampos();
    }
    private void carregarComboTipos() {
    List<TipoProduto> tipos = new TipoProdutoDAO().listarTipos();
    for (TipoProduto t : tipos) {
        jCBTipo.addItem(t);
    }
    }
    //1. preenche os campos com os dados do produto selecionado na tabela
    private void preencherCampos() {
        jTFId.setText(String.valueOf(produto.getId()));
        jTFId.setEditable(false); //ID não deve ser alterado
        jTFDescricao.setText(produto.getDescricao());
        jTFValorUnitario.setText(String.valueOf(produto.getValorUnitario()));
        jTFQuantidade.setText(String.valueOf(produto.getQuantidade()));

    //2. seleciona no combo o tipo que já é o do produto
        for (int i = 0; i < jCBTipo.getItemCount(); i++) {
            TipoProduto t = jCBTipo.getItemAt(i);
            if (t.getId() == produto.getTipoId()) {
                jCBTipo.setSelectedItem(t);
                break;
            }
        }
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLId = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jLDescricao = new javax.swing.JLabel();
        jTFDescricao = new javax.swing.JTextField();
        jLQuantidade = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLTipo = new javax.swing.JLabel();
        jLValorUnitario = new javax.swing.JLabel();
        jTFValorUnitario = new javax.swing.JTextField();
        jBAtualizarCadastro = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLId.setText("ID");

        jTFId.setEditable(false);
        jTFId.setText("Não Editável");

        jLDescricao.setText("Nome");

        jLQuantidade.setText("Quantidade");

        jLTipo.setText("Tipo");

        jLValorUnitario.setText("Valor Unitário");

        jBAtualizarCadastro.setText("Atualizar Cadastro");
        jBAtualizarCadastro.addActionListener(this::jBAtualizarCadastroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBAtualizarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFId)
                            .addComponent(jTFDescricao)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addComponent(jTFQuantidade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLDescricao)
                    .addComponent(jLValorUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBAtualizarCadastro)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAtualizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarCadastroActionPerformed
        // TODO add your handling code here:
        //2. valida campos vazios (tipo agora vem do combo, não precisa checar texto)
        if (jTFDescricao.getText().isEmpty() || jTFValorUnitario.getText().isEmpty()
            || jTFQuantidade.getText().isEmpty() || jCBTipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            //3. converte e atualiza o objeto produto
            produto.setDescricao(jTFDescricao.getText());
            produto.setValorUnitario(Double.parseDouble(jTFValorUnitario.getText()));
            produto.setQuantidade(Integer.parseInt(jTFQuantidade.getText()));

            //3b. pega o tipo selecionado no combo e extrai o ID real
            TipoProduto tipoSelecionado = (TipoProduto) jCBTipo.getSelectedItem();
            produto.setTipoId(tipoSelecionado.getId());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //4. salva no banco
        new ProdutoDAO().alterarProduto(produto);
        JOptionPane.showMessageDialog(this, "Produto alterado com sucesso!");
        //5. atualiza a tabela da tela de consulta e fecha o diálogo
        telaConsulta.carregarTabela();
        dispose();
    }//GEN-LAST:event_jBAtualizarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizarCadastro;
    private javax.swing.JComboBox<TipoProduto> jCBTipo;
    private javax.swing.JLabel jLDescricao;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLValorUnitario;
    private javax.swing.JTextField jTFDescricao;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextField jTFValorUnitario;
    // End of variables declaration//GEN-END:variables
}
