/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.FornecedorDAO;
import com.mycompany.appsistemaestoque.model.Fornecedor;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Henrique
 */
public class FornecedorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form FornecedorView
     */
    public FornecedorView() {
        initComponents();
         try {
            MaskFormatter maskTelefone = new MaskFormatter("(##) #####-####");
            maskTelefone.setPlaceholderCharacter('_');
            jTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(maskTelefone));
            
            MaskFormatter maskCNPJ = new MaskFormatter("##.###.###/####-##");
            maskCNPJ.setPlaceholderCharacter('_');
            jTCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(maskCNPJ));
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLID = new javax.swing.JLabel();
        jLRazaoSocial = new javax.swing.JLabel();
        jLCNPJ = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jTRazaoSocial = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JFormattedTextField();
        jTCNPJ = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLID.setText("ID:");

        jLRazaoSocial.setText("Razão Social:");

        jLCNPJ.setText("CNPJ:");

        jLTelefone.setText("Telefone:");

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(this::jBCadastrarActionPerformed);

        try {
            jTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTTelefone.setToolTipText("");

        try {
            jTCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##  ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        try {
        // Criar um novo fornecedor
        Fornecedor fornecedor = new Fornecedor();
        
        // Preencher com dados dos campos
        String idText = jTID.getText().trim();
        if (!idText.isEmpty()) {
            fornecedor.setID(Integer.parseInt(idText));
        }
        
        fornecedor.setRazaoSocial(jTRazaoSocial.getText().trim());
        fornecedor.setCNPJ(jTCNPJ.getText().trim());
        fornecedor.setTelefone(jTTelefone.getText().trim());
        
        // Valida campos vazios antes de converter
        if (jTCNPJ.getText().isEmpty() || jTID.getText().isEmpty() || jTRazaoSocial.getText().isEmpty()
            || jTTelefone.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Salvar no banco
        new FornecedorDAO().cadastrar(fornecedor);
        
        // Mostrar mensagem de sucesso
        JOptionPane.showMessageDialog(this, 
            "Fornecedor cadastrado com sucesso!", 
            "Sucesso", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Limpar campos
        jTID.setText("");
        jTCNPJ.setText("");
        jTTelefone.setText("");
        jTRazaoSocial.setText("");
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "ID deve ser um número válido", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Erro de validação", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao cadastrar fornecedor: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JLabel jLCNPJ;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLRazaoSocial;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JFormattedTextField jTCNPJ;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTRazaoSocial;
    private javax.swing.JFormattedTextField jTTelefone;
    // End of variables declaration//GEN-END:variables
}
