/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.dao.FornecedorDAO;
import com.mycompany.appsistemaestoque.model.Fornecedor;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Henrique
 */
public class FornecedorView extends javax.swing.JInternalFrame {

    private boolean modoEdicao = false;
    /**
     * Creates new form FornecedorView
     */
    public FornecedorView() {
        initComponents();
         try {
            MaskFormatter maskTelefone = new MaskFormatter("(##) #####-####");
            maskTelefone.setPlaceholderCharacter('_');
            jTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(maskTelefone));
            
            MaskFormatter maskCNPJ = new MaskFormatter("##.###.###/####-##");
            maskCNPJ.setPlaceholderCharacter('_');
            jTCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(maskCNPJ));
            
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
     public FornecedorView(Fornecedor fornecedorParaEditar) {
        this(); // reaproveita o construtor de cima (initComponents + máscaras)
 
        modoEdicao = true;
        setTitle("Alterar Fornecedor");
        jBCadastrar.setText("Alterar");
 
        // preenche os campos com os dados do fornecedor selecionado na consulta
        jTID.setText(String.valueOf(fornecedorParaEditar.getID()));
        jTRazaoSocial.setText(fornecedorParaEditar.getRazaoSocial());
        jTCNPJ.setText(fornecedorParaEditar.getCNPJ());
        jTTelefone.setText(fornecedorParaEditar.getTelefone());
 
        // não deixa mudar o ID, senão a alteração vai bater num fornecedor errado
        jTID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLID = new javax.swing.JLabel();
        jLRazaoSocial = new javax.swing.JLabel();
        jLCNPJ = new javax.swing.JLabel();
        jLTelefone = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jTRazaoSocial = new javax.swing.JTextField();
        jTTelefone = new javax.swing.JFormattedTextField();
        jTCNPJ = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Fornecedor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLID.setText("ID:");

        jLRazaoSocial.setText("Razão Social:");

        jLCNPJ.setText("CNPJ:");

        jLTelefone.setText("Telefone:");

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(this::jBCadastrarActionPerformed);

        try {
            jTTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTTelefone.setToolTipText("");

        try {
            jTCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##  ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTelefone)
                                    .addComponent(jLID)
                                    .addComponent(jLCNPJ))
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLRazaoSocial)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTRazaoSocial)
                            .addComponent(jTID)
                            .addComponent(jTTelefone)
                            .addComponent(jTCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLID)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRazaoSocial)
                    .addComponent(jTRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCNPJ)
                    .addComponent(jTCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTelefone)
                    .addComponent(jTTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jBCadastrar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        try {
        // Valida campos vazios ANTES de montar o objeto
        if (jTID.getText().trim().isEmpty()
            || jTRazaoSocial.getText().trim().isEmpty()
            || jTCNPJ.getText().contains("_")
            || jTTelefone.getText().contains("_")) {
 
            JOptionPane.showMessageDialog(this, "Todos os campos devem ser preenchidos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Criar o fornecedor com os dados da tela
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setID(Integer.parseInt(jTID.getText().trim()));
        fornecedor.setRazaoSocial(jTRazaoSocial.getText().trim());
        fornecedor.setCNPJ(jTCNPJ.getText().trim());
        fornecedor.setTelefone(jTTelefone.getText().trim());
 
        // Se veio da tela de Consulta (modoEdicao), atualiza; senão, cadastra novo
        if (modoEdicao) {
            new FornecedorDAO().alterar(fornecedor);
            JOptionPane.showMessageDialog(this,
                "Fornecedor alterado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
            dispose(); // fecha a tela de edição e volta pra consulta
            return;
        }
 
        new FornecedorDAO().cadastrar(fornecedor);
        
        JOptionPane.showMessageDialog(this, 
            "Fornecedor cadastrado com sucesso!", 
            "Sucesso", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Limpar campos
        jTID.setText("");
        jTCNPJ.setText("");
        jTTelefone.setText("");
        jTRazaoSocial.setText("");
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "ID deve ser um número válido", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Erro de validação", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao cadastrar fornecedor: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JLabel jLCNPJ;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLRazaoSocial;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JFormattedTextField jTCNPJ;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTRazaoSocial;
    private javax.swing.JFormattedTextField jTTelefone;
    // End of variables declaration//GEN-END:variables
}
