package com.mycompany.appsistemaestoque.view;

 
import com.mycompany.appsistemaestoque.dao.FornecedorDAO;
import com.mycompany.appsistemaestoque.dao.ItemNotaEntradaDAO;
import com.mycompany.appsistemaestoque.dao.NotaEntradaDAO;
import com.mycompany.appsistemaestoque.dao.ProdutoDAO;
import com.mycompany.appsistemaestoque.dao.TipoProdutoDAO;
import com.mycompany.appsistemaestoque.model.Fornecedor;
import com.mycompany.appsistemaestoque.model.NotaEntrada;
import com.mycompany.appsistemaestoque.model.Produto;
import com.mycompany.appsistemaestoque.model.TipoProduto;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author caioh
 */
public class NotaEntradaView extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form GerenciaNotaEntradaView
     */
    public NotaEntradaView() {
        initComponents();
        
        
        ((DefaultTableModel) jTProdutos.getModel()).setRowCount(0);
    
        // Remove o modelo que o NetBeans colocou (com Strings)
        jCBFornecedores.setModel(new DefaultComboBoxModel<>());
        jCBTipoProduto.setModel(new DefaultComboBoxModel<>());
        jCBProduto.setModel(new DefaultComboBoxModel<>());
        
        jCBTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarComboProdutosPorTipo();
            }
        });

        // Agora preenche com seus objetos
        carregarComboFornecedores();
        carregarComboTipos();
        carregarComboProdutosPorTipo();
    }
    
    // 1. Preenche o combo de fornecedores com os dados do banco
    private void carregarComboFornecedores() {
        jCBFornecedores.removeAllItems(); // Limpa tudo
        List<Fornecedor> fornecedores = new FornecedorDAO().listar();
        for (Fornecedor f : fornecedores) {
            jCBFornecedores.addItem(f); // Adiciona o objeto Fornecedor
        }
    }

    private void carregarComboTipos() {
        jCBTipoProduto.removeAllItems();
        List<TipoProduto> tipos = new TipoProdutoDAO().listarTipos();
        for (TipoProduto t : tipos) {
            jCBTipoProduto.addItem(t); // Adiciona o objeto TipoProduto
        }
    }

    private void carregarComboProdutosPorTipo() {
        jCBProduto.removeAllItems();

        TipoProduto tipoSelecionado = (TipoProduto) jCBTipoProduto.getSelectedItem();
        if (tipoSelecionado == null) {
            return;
        }

        List<Produto> produtos = new ProdutoDAO().listarPorTipo(tipoSelecionado.getId());
        for (Produto p : produtos) {
            jCBProduto.addItem(p); // Adiciona o objeto Produto
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLFornecedores = new javax.swing.JLabel();
        jLTipoProduto = new javax.swing.JLabel();
        jLProduto = new javax.swing.JLabel();
        jLQuantidade = new javax.swing.JLabel();
        jSQuantidade = new javax.swing.JSpinner();
        jBAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jBCadastrar = new javax.swing.JButton();
        jCBFornecedores = new javax.swing.JComboBox<>();
        jCBTipoProduto = new javax.swing.JComboBox<>();
        jCBProduto = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Nota de Entrada");

        jLFornecedores.setText("Fornecedores:");

        jLTipoProduto.setText("Tipo de Produto:");

        jLProduto.setText("Produto:");

        jLQuantidade.setText("Quantidade:");

        jBAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(this::jBAdicionarActionPerformed);

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Produto", "Descrição", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(this::jBCadastrarActionPerformed);

        jCBProduto.addActionListener(this::jCBProdutoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jBAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLTipoProduto)))))
                    .addComponent(jCBFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLProduto)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFornecedores)
                    .addComponent(jLTipoProduto)
                    .addComponent(jLProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCadastrar))))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        // TODO add your handling code here:
        Produto produtoSelecionado = (Produto) jCBProduto.getSelectedItem();
        if (produtoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um produto para adicionar!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        int quantidade = (Integer) jSQuantidade.getValue();
        if (quantidade <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade precisa ser maior que zero!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // calcula o valor total desse item (valor unitário do produto x quantidade)
        double valorTotalItem = produtoSelecionado.getValorUnitario() * quantidade;
 
        // adiciona a linha na tabela (ID, Descrição, Quantidade, Total)
        DefaultTableModel model = (DefaultTableModel) jTProdutos.getModel();
        model.addRow(new Object[]{
            produtoSelecionado.getId(),
            produtoSelecionado.getDescricao(),
            quantidade,
            valorTotalItem
        });
 
        // volta o spinner pra 1, pronto pro próximo produto
        jSQuantidade.setValue(1);               
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        Fornecedor fornecedorSelecionado = (Fornecedor) jCBFornecedores.getSelectedItem();
        if (fornecedorSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um fornecedor!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        DefaultTableModel model = (DefaultTableModel) jTProdutos.getModel();
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Adicione pelo menos um produto antes de cadastrar!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
 
        // soma o valor total da nota (soma do "Total" de cada linha da tabela)
        double valorTotalNota = 0.0;
        for (int i = 0; i < model.getRowCount(); i++) {
            valorTotalNota += (Double) model.getValueAt(i, 3);
        }
 
        // monta e salva a Nota de Entrada (data de hoje, gerada pelo sistema)
        NotaEntrada nota = new NotaEntrada();
        nota.setDataEntrada(LocalDate.now());
        nota.setValorTotal(valorTotalNota);
        nota.setIdFornecedor(fornecedorSelecionado.getID());
 
        NotaEntradaDAO notaDao = new NotaEntradaDAO();
        notaDao.cadastrarNotaEntrada(nota); // depois disso, nota.getId() já vem preenchido
 
        ItemNotaEntradaDAO itemDao = new ItemNotaEntradaDAO(); // Variável criada como itemDao
        
        for (int i = 0; i < model.getRowCount(); i++) {
            int idProduto = (Integer) model.getValueAt(i, 0);
            int qtd = (Integer) model.getValueAt(i, 2);
            
            // Usamos a mesma variável itemDao para chamar o método
            itemDao.cadastrar(nota.getId(), idProduto, qtd);
        }

        JOptionPane.showMessageDialog(this, "Nota de Entrada cadastrada com sucesso!");
 
        JOptionPane.showMessageDialog(this, "Nota de Entrada cadastrada com sucesso!");
 
        // limpa tudo pra começar uma nova nota
        model.setRowCount(0);
        if (jCBFornecedores.getItemCount() > 0) {
            jCBFornecedores.setSelectedIndex(0);
        }
        if (jCBTipoProduto.getItemCount() > 0) {
            jCBTipoProduto.setSelectedIndex(0);
        }
        jSQuantidade.setValue(1);
             
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jCBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProdutoActionPerformed
        // TODO add your handling code here:
        carregarComboProdutosPorTipo();
    }//GEN-LAST:event_jCBProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JComboBox<Fornecedor> jCBFornecedores;
    private javax.swing.JComboBox<Produto> jCBProduto;
    private javax.swing.JComboBox<TipoProduto> jCBTipoProduto;
    private javax.swing.JLabel jLFornecedores;
    private javax.swing.JLabel jLProduto;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLTipoProduto;
    private javax.swing.JSpinner jSQuantidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    // End of variables declaration//GEN-END:variables
}
