/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

import com.mycompany.appsistemaestoque.model.Produto;


/**
 *
 * @author Henrique
 */
public class TelaPrincipalView extends javax.swing.JFrame {
    
    /*
    ███╗   ██╗  ██████╗  ████████╗  █████╗  ███████╗
    ████╗  ██║ ██╔═══██╗ ╚══██╔══╝ ██╔══██╗ ██╔════╝
    ██╔██╗ ██║ ██║   ██║    ██║    ███████║ ███████╗
    ██║╚██╗██║ ██║   ██║    ██║    ██╔══██║ ╚════██║
    ██║ ╚████║ ╚██████╔╝    ██║    ██║  ██║ ███████║
    ╚═╝  ╚═══╝  ╚═════╝     ╚═╝    ╚═╝  ╚═╝ ╚══════╝
   */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName());
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdFundo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMFornecedor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMTipoProduto = new javax.swing.JMenuItem();
        jMProduto = new javax.swing.JMenuItem();
        jMNotaEntrada = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMConsultaFornecedor = new javax.swing.JMenuItem();
        jMConsultaTipoProduto = new javax.swing.JMenuItem();
        jMConsultaProdutos = new javax.swing.JMenuItem();
        jMConsultaNotaEntrada = new javax.swing.JMenuItem();
        jMConsultaItensNotaEntrada = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdFundoLayout = new javax.swing.GroupLayout(jdFundo);
        jdFundo.setLayout(jdFundoLayout);
        jdFundoLayout.setHorizontalGroup(
            jdFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        jdFundoLayout.setVerticalGroup(
            jdFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jMenu1.setText("Arquivo");

        jMenu4.setText("Sair");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMFornecedor.setText("Cadastro");

        jMenuItem1.setText("Fornecedor");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMFornecedor.add(jMenuItem1);

        jMTipoProduto.setText("Tipo de Produto");
        jMTipoProduto.addActionListener(this::jMTipoProdutoActionPerformed);
        jMFornecedor.add(jMTipoProduto);

        jMProduto.setText("Produto");
        jMProduto.addActionListener(this::jMProdutoActionPerformed);
        jMFornecedor.add(jMProduto);

        jMNotaEntrada.setText("Nota de Entrada");
        jMFornecedor.add(jMNotaEntrada);

        jMenuBar1.add(jMFornecedor);

        jMenu3.setText("Consulta");

        jMConsultaFornecedor.setText("Fornecedores");
        jMConsultaFornecedor.addActionListener(this::jMConsultaFornecedorActionPerformed);
        jMenu3.add(jMConsultaFornecedor);

        jMConsultaTipoProduto.setText("Tipos de Produto");
        jMConsultaTipoProduto.addActionListener(this::jMConsultaTipoProdutoActionPerformed);
        jMenu3.add(jMConsultaTipoProduto);

        jMConsultaProdutos.setText("Produtos");
        jMConsultaProdutos.addActionListener(this::jMConsultaProdutosActionPerformed);
        jMenu3.add(jMConsultaProdutos);

        jMConsultaNotaEntrada.setText("Notas de Entrada");
        jMenu3.add(jMConsultaNotaEntrada);

        jMConsultaItensNotaEntrada.setText("Itens Nota de Entrada");
        jMenu3.add(jMConsultaItensNotaEntrada);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMProdutoActionPerformed
        // TODO add your handling code here:
        ProdutoView form = new ProdutoView(); //CRIA UMA NOVA INSTÂNCIA
        jdFundo.add(form); // Adiciona a janela ao JDesktopPane da aplicação
        form.setVisible(true);// Torna a janela visível para o usuário
    }//GEN-LAST:event_jMProdutoActionPerformed


    private void jMTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTipoProdutoActionPerformed
        // TODO add your handling code here:
        //Cria a instância da sua tela de Tipo de Produto
        TipoProdutoView telaTipo = new TipoProdutoView();

        // 2. Adiciona essa tela dentro do painel principal da área de trabalho
        // ATENÇÃO: Confirme se o nome do seu painel de fundo é jDesktopPane1
        jdFundo.add(telaTipo);

        //Torna a tela visível para o usuário
        telaTipo.setVisible(true);
        
    }//GEN-LAST:event_jMTipoProdutoActionPerformed

    private void jMConsultaTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaTipoProdutoActionPerformed
        // TODO add your handling code here:
        ConsultaTipoProdutoView telaConsulta = new ConsultaTipoProdutoView();
        jdFundo.add(telaConsulta);
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_jMConsultaTipoProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FornecedorView form = new FornecedorView(); //CRIA UMA NOVA INSTÂNCIA
        jdFundo.add(form); // Adiciona a janela ao JDesktopPane da aplicação
        form.setVisible(true);// Torna a janela visível para o usuário
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaProdutosActionPerformed
        // TODO add your handling code here:
        ConsultaProdutos consultaView = new ConsultaProdutos();
        jdFundo.add(consultaView);
        consultaView.setVisible(true);
    }//GEN-LAST:event_jMConsultaProdutosActionPerformed

    private void jMConsultaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaFornecedorActionPerformed
        // TODO add your handling code here:
        ConsultaFornecedor consultaView = new ConsultaFornecedor();
        jdFundo.add(consultaView);
        consultaView.setVisible(true);
    }//GEN-LAST:event_jMConsultaFornecedorActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMConsultaFornecedor;
    private javax.swing.JMenuItem jMConsultaItensNotaEntrada;
    private javax.swing.JMenuItem jMConsultaNotaEntrada;
    private javax.swing.JMenuItem jMConsultaProdutos;
    private javax.swing.JMenuItem jMConsultaTipoProduto;
    private javax.swing.JMenu jMFornecedor;
    private javax.swing.JMenuItem jMNotaEntrada;
    private javax.swing.JMenuItem jMProduto;
    private javax.swing.JMenuItem jMTipoProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdFundo;
    // End of variables declaration//GEN-END:variables
    
   
}
