/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appsistemaestoque.view;

/**
 *
 * @author Henrique
 */
public class TipoProdutoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form TipoProdutoView
     */
    public TipoProdutoView() {
        initComponents();
    }
    // Variável para guardar o ID que está sendo alterado
    public int idAlteracao = 0; 

    // NOVO Construtor que recebe o ID
    public TipoProdutoView(int id) {
        initComponents();
        this.idAlteracao = id; // Guarda o ID para quando clicar em "Salvar"
        
        try {
            com.mycompany.appsistemaestoque.dao.TipoProdutoDAO dao = new com.mycompany.appsistemaestoque.dao.TipoProdutoDAO();
            com.mycompany.appsistemaestoque.model.TipoProduto tp = dao.buscarPorId(id);
            
            
            txtDescricao.setText(tp.getDescricao()); 
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tipo de Produto");

        jLabel1.setText("Descrição: ");

        txtDescricao.setColumns(5);
        txtDescricao.addActionListener(this::txtDescricaoActionPerformed);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnCadastrar)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:                                             
        try {
            com.mycompany.appsistemaestoque.model.TipoProduto tp = new com.mycompany.appsistemaestoque.model.TipoProduto();
            
            //jTextField1 se a sua caixinha de texto tiver outro nome
            tp.setDescricao(txtDescricao.getText()); 
            
            com.mycompany.appsistemaestoque.dao.TipoProdutoDAO dao = new com.mycompany.appsistemaestoque.dao.TipoProdutoDAO();
            
            // AQUI É O SEGREDO: Verifica a variável idAlteracao
            if (this.idAlteracao == 0) {
                // Se a variável for 0, é porque não veio de uma tabela. É cadastro novo!
                dao.cadastrar(tp);
            } else {
                // Se a variável tiver um número (ex: 12), o sistema entra aqui e ALTERA!
                tp.setId(this.idAlteracao); 
                dao.alterar(tp);
                
                // Limpa o ID para não causar problemas no futuro
                this.idAlteracao = 0; 
            }
            
            txtDescricao.setText(""); // Limpa o campo
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar os dados: " + e.getMessage());
        }
    
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:                                
        // Verifica se o campo está vazio (o .trim() tira os espaços em branco)
        if (txtDescricao.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "O campo de descrição não pode ficar em branco!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            txtDescricao.requestFocus(); // Faz o cursor voltar a piscar no campo
            return; // Para a execução do código aqui, impedindo que salve vazio
        }
        
        try {
            com.mycompany.appsistemaestoque.model.TipoProduto tp = new com.mycompany.appsistemaestoque.model.TipoProduto();
            
            // Pega o que foi digitado na tela
            tp.setDescricao(txtDescricao.getText()); 
            
            com.mycompany.appsistemaestoque.dao.TipoProdutoDAO dao = new com.mycompany.appsistemaestoque.dao.TipoProdutoDAO();
            
            // AQUI É O SEGREDO: Verifica a variável idAlteracao
            if (this.idAlteracao == 0) {
                // Se a variável for 0, é porque não veio de uma tabela. É cadastro novo!
                dao.cadastrar(tp);
                javax.swing.JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
            } else {
                // Se a variável tiver um número, o sistema entra aqui e ALTERA!
                tp.setId(this.idAlteracao); 
                dao.alterar(tp);
                javax.swing.JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                
                // Limpa o ID para não causar problemas no futuro
                this.idAlteracao = 0; 
            }
            
            txtDescricao.setText(""); // Limpa o campo
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar os dados: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables
}

